name: 주식 리포트 주2일 자동 발송

on:
  schedule:
    # 한국 시간 기준 월요일, 목요일 오전 8시 실행 설정
    - cron: '0 23 * * 0,3'
  workflow_dispatch: # 내가 원할 때 버튼 눌러서 실행하는 기능

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 코드 가져오기
        uses: actions/checkout@v3

      - name: 파이썬 설치
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 한글 폰트 및 필수 도구 설치
        run: |
          sudo apt-get install -y fonts-nanum
          pip install yfinance requests matplotlib seaborn

      - name: 주식 로봇 실행
        env:
          NAVER_ID: ${{ secrets.NAVER_ID }}
          NAVER_SECRET: ${{ secrets.NAVER_SECRET }}
          NAVER_USER: ${{ secrets.NAVER_USER }}
          NAVER_PW: ${{ secrets.NAVER_PW }}
          RECIPIENTS: ${{ secrets.RECIPIENTS }}
        run: python main.py
